-- Initialize booking_provider table

INSERT IGNORE INTO `booking_provider` (`name`) VALUES ('VIATOR');

-- Initialize country table

INSERT IGNORE INTO country (id, country_calling_code) VALUES (1, '+4');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (2, '+248');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (3, '+8');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (4, '+12');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (5, '+16');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (6, '+20');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (7, '+24');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (8, '+660');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (9, '+10');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (10, '+28');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (11, '+32');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (12, '+51');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (13, '+533');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (14, '+36');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (15, '+40');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (16, '+31');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (17, '+44');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (18, '+48');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (19, '+50');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (20, '+52');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (21, '+112');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (22, '+56');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (23, '+84');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (24, '+204');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (25, '+60');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (26, '+64');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (27, '+68');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (28, '+535');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (29, '+70');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (30, '+72');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (31, '+74');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (32, '+76');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (33, '+86');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (34, '+96');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (35, '+100');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (36, '+854');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (37, '+108');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (38, '+132');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (39, '+116');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (40, '+120');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (41, '+124');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (42, '+136');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (43, '+140');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (44, '+148');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (45, '+152');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (46, '+156');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (47, '+162');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (48, '+166');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (49, '+170');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (50, '+174');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (51, '+178');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (52, '+180');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (53, '+184');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (54, '+188');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (55, '+384');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (56, '+191');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (57, '+192');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (58, '+531');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (59, '+196');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (60, '+203');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (61, '+208');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (62, '+262');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (63, '+212');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (64, '+214');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (65, '+218');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (66, '+818');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (67, '+222');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (68, '+226');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (69, '+232');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (70, '+233');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (71, '+748');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (72, '+231');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (73, '+238');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (74, '+234');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (75, '+242');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (76, '+246');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (77, '+250');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (78, '+254');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (79, '+258');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (80, '+260');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (81, '+266');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (82, '+270');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (83, '+268');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (84, '+276');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (85, '+288');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (86, '+292');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (87, '+300');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (88, '+304');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (89, '+308');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (90, '+312');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (91, '+316');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (92, '+320');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (93, '+831');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (94, '+324');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (95, '+624');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (96, '+328');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (97, '+332');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (98, '+334');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (99, '+336');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (100, '+340');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (101, '+344');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (102, '+348');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (103, '+352');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (104, '+356');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (105, '+360');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (106, '+364');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (107, '+368');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (108, '+372');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (109, '+833');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (110, '+376');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (111, '+380');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (112, '+388');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (113, '+392');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (114, '+832');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (115, '+400');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (116, '+398');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (117, '+404');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (118, '+296');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (119, '+408');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (120, '+410');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (121, '+414');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (122, '+417');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (123, '+418');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (124, '+428');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (125, '+422');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (126, '+426');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (127, '+430');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (128, '+434');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (129, '+438');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (130, '+440');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (131, '+442');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (132, '+446');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (133, '+450');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (134, '+454');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (135, '+458');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (136, '+462');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (137, '+466');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (138, '+470');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (139, '+584');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (140, '+474');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (141, '+478');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (142, '+480');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (143, '+175');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (144, '+484');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (145, '+583');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (146, '+498');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (147, '+492');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (148, '+496');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (149, '+499');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (150, '+500');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (151, '+504');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (152, '+508');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (153, '+104');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (154, '+516');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (155, '+520');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (156, '+524');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (157, '+528');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (158, '+540');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (159, '+554');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (160, '+558');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (161, '+562');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (162, '+566');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (163, '+570');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (164, '+574');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (165, '+807');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (166, '+580');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (167, '+578');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (168, '+512');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (169, '+586');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (170, '+585');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (171, '+275');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (172, '+591');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (173, '+598');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (174, '+600');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (175, '+604');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (176, '+608');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (177, '+612');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (178, '+616');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (179, '+620');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (180, '+630');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (181, '+634');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (182, '+638');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (183, '+642');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (184, '+643');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (185, '+646');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (186, '+652');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (187, '+654');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (188, '+659');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (189, '+662');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (190, '+663');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (191, '+666');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (192, '+670');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (193, '+882');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (194, '+674');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (195, '+678');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (196, '+682');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (197, '+686');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (198, '+688');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (199, '+690');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (200, '+694');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (201, '+702');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (202, '+534');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (203, '+703');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (204, '+705');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (205, '+90');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (206, '+706');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (207, '+710');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (208, '+239');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (209, '+728');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (210, '+724');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (211, '+144');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (212, '+729');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (213, '+740');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (214, '+744');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (215, '+752');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (216, '+756');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (217, '+760');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (218, '+158');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (219, '+762');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (220, '+834');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (221, '+764');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (222, '+626');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (223, '+768');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (224, '+772');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (225, '+776');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (226, '+780');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (227, '+788');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (228, '+792');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (229, '+795');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (230, '+796');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (231, '+798');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (232, '+800');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (233, '+804');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (234, '+784');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (235, '+826');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (236, '+840');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (237, '+581');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (238, '+858');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (239, '+860');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (240, '+548');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (241, '+862');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (242, '+704');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (243, '+92');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (244, '+850');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (245, '+876');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (246, '+732');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (247, '+887');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (248, '+894');
INSERT IGNORE INTO country (id, country_calling_code) VALUES (249, '+716');

-- Initialize country_translation table

INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (1, 'en', 'Afghanistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (1, 'fr', 'Afghanistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (2, 'en', 'Åland Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (2, 'fr', 'Îles Åland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (3, 'en', 'Albania');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (3, 'fr', 'Albanie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (4, 'en', 'Algeria');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (4, 'fr', 'Algérie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (5, 'en', 'American Samoa');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (5, 'fr', 'Samoa américaines');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (6, 'en', 'Andorra');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (6, 'fr', 'Andorre');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (7, 'en', 'Angola');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (7, 'fr', 'Angola');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (8, 'en', 'Anguilla');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (8, 'fr', 'Anguilla');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (9, 'en', 'Antarctica');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (9, 'fr', 'Antarctique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (10, 'en', 'Antigua and Barbuda');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (10, 'fr', 'Antigua-et-Barbuda');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (11, 'en', 'Argentina');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (11, 'fr', 'Argentine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (12, 'en', 'Armenia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (12, 'fr', 'Arménie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (13, 'en', 'Aruba');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (13, 'fr', 'Aruba');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (14, 'en', 'Australia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (14, 'fr', 'Australie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (15, 'en', 'Austria');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (15, 'fr', 'Autriche');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (16, 'en', 'Azerbaijan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (16, 'fr', 'Azerbaïdjan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (17, 'en', 'Bahamas');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (17, 'fr', 'Bahamas');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (18, 'en', 'Bahrain');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (18, 'fr', 'Bahreïn');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (19, 'en', 'Bangladesh');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (19, 'fr', 'Bangladesh');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (20, 'en', 'Barbados');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (20, 'fr', 'Barbade');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (21, 'en', 'Belarus');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (21, 'fr', 'Biélorussie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (22, 'en', 'Belgium');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (22, 'fr', 'Belgique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (23, 'en', 'Belize');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (23, 'fr', 'Belize');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (24, 'en', 'Benin');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (24, 'fr', 'Bénin');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (25, 'en', 'Bermuda');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (25, 'fr', 'Bermudes');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (26, 'en', 'Bhutan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (26, 'fr', 'Bhoutan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (27, 'en', 'Bolivia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (27, 'fr', 'Bolivie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (28, 'en', 'Bonaire');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (28, 'fr', 'Bonaire');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (29, 'en', 'Bosnia and Herzegovina');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (29, 'fr', 'Bosnie et Herzégovine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (30, 'en', 'Botswana');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (30, 'fr', 'Botswana');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (31, 'en', 'Bouvet Island');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (31, 'fr', 'Île Bouvet');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (32, 'en', 'Brazil');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (32, 'fr', 'Brésil');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (33, 'en', 'British Indian Ocean Territory');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) Values (33, 'fr', 'Territoire Britannique De l''Océan Indien');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (34, 'en', 'Brunei Darussalam');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (34, 'fr', 'Brunei Darussalam');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (35, 'en', 'Bulgaria');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (35, 'fr', 'Bulgarie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (36, 'en', 'Burkina Faso');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (36, 'fr', 'Burkina Faso');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (37, 'en', 'Burundi');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (37, 'fr', 'Burundi');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (38, 'en', 'Cabo Verde');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (38, 'fr', 'Cap Vert');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (39, 'en', 'Cambodia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (39, 'fr', 'Cambodge');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (40, 'en', 'Cameroon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (40, 'fr', 'Cameroun');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (41, 'en', 'Canada');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (41, 'fr', 'Canada');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (42, 'en', 'Cayman Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (42, 'fr', 'Îles  Cayman');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (43, 'en', 'Central African Republic');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (43, 'fr', 'République centrafricaine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (44, 'en', 'Chad');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (44, 'fr', 'Tchad');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (45, 'en', 'Chile');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (45, 'fr', 'Chili');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (46, 'en', 'China');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (46, 'fr', 'Chine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (47, 'en', 'Christmas Island');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (47, 'fr', 'Îles Christmas');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (48, 'en', 'Cocos (Keeling) Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (48, 'fr', 'Îles Cocos (Keeling)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (49, 'en', 'Colombia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (49, 'fr', 'Colombie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (50, 'en', 'Comoros');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (50, 'fr', 'Comores');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (51, 'en', 'Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (51, 'fr', 'Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (52, 'en', 'Congo, Democratic Republic of');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (52, 'fr', 'Congo, République démocratique du');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (53, 'en', 'Cook Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (53, 'fr', 'Îles Cook');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (54, 'en', 'Costa Rica');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (54, 'fr', 'Costa Rica');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (55, 'en', 'Côte d''Ivoire');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (55, 'fr', 'Côte d''Ivoire');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (56, 'en', 'Croatia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (56, 'fr', 'Croatie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (57, 'en', 'Cuba');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (57, 'fr', 'Cuba');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (58, 'en', 'Curaçao');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (58, 'fr', 'Curaçao');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (59, 'en', 'Cyprus');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (59, 'fr', 'Chypre');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (60, 'en', 'Czechia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (60, 'fr', 'République tchéque');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (61, 'en', 'Denmark');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (61, 'fr', 'Danemark');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (62, 'en', 'Djibouti');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (62, 'fr', 'Djibouti');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (63, 'en', 'Dominica');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (63, 'fr', 'Dominique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (64, 'en', 'Dominican Republic');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (64, 'fr', 'République dominicaine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (65, 'en', 'Ecuador');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (65, 'fr', 'Équateur');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (66, 'en', 'Egypt');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (66, 'fr', 'Égypte');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (67, 'en', 'El Salvador');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (67, 'fr', 'El Salvador');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (68, 'en', 'Equatorial Guinea');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (68, 'fr', 'Guinée équatoriale');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (69, 'en', 'Eritrea');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (69, 'fr', 'Érythrée');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (70, 'en', 'Estonia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (70, 'fr', 'Estonie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (71, 'en', 'Eswatini');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (71, 'fr', 'Eswatini');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (72, 'en', 'Ethiopia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (72, 'fr', 'Éthiopie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (73, 'en', 'Falkland Islands (Malvinas)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (73, 'fr', 'Îles Falkland (Malvinas)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (74, 'en', 'Faroe Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (74, 'fr', 'Îles Féroé');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (75, 'en', 'Fiji');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (75, 'fr', 'Fidji');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (76, 'en', 'Finland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (76, 'fr', 'Finlande');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (77, 'en', 'France');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (77, 'fr', 'France');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (78, 'en', 'French Guiana');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (78, 'fr', 'Guyane française');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (79, 'en', 'French Polynesia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (79, 'fr', 'Polynésie française');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (80, 'en', 'French Southern Territories');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (80, 'fr', 'Terres australes françaises');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (81, 'en', 'Gabon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (81, 'fr', 'Gabon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (82, 'en', 'Gambia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (82, 'fr', 'Gambie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (83, 'en', 'Georgia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (83, 'fr', 'Géorgie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (84, 'en', 'Germany');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (84, 'fr', 'Allemagne');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (85, 'en', 'Ghana');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (85, 'fr', 'Ghana');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (86, 'en', 'Gibraltar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (86, 'fr', 'Gibraltar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (87, 'en', 'Greece');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (87, 'fr', 'Grèce');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (88, 'en', 'Greenland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (88, 'fr', 'Groenland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (89, 'en', 'Grenada');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (89, 'fr', 'Grenade');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (90, 'en', 'Guadeloupe');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (90, 'fr', 'Guadeloupe');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (91, 'en', 'Guam');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (91, 'fr', 'Guam');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (92, 'en', 'Guatemala');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (92, 'fr', 'Guatemala');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (93, 'en', 'Guernsey');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (93, 'fr', 'Guernesey');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (94, 'en', 'Guinea');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (94, 'fr', 'Guinée');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (95, 'en', 'Guinea-Bissau');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (95, 'fr', 'Guinée-Bissau');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (96, 'en', 'Guyana');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (96, 'fr', 'Guyane');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (97, 'en', 'Haiti');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (97, 'fr', 'Haïti');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (98, 'en', 'Heard Island and McDonald Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (98, 'fr', 'Îles Heard et McDonald');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (99, 'en', 'Holy See');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (99, 'fr', 'Saint Siège');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (100, 'en', 'Honduras');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (100, 'fr', 'Honduras');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (101, 'en', 'Hong Kong');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (101, 'fr', 'Hong Kong');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (102, 'en', 'Hungary');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (102, 'fr', 'Hongrie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (103, 'en', 'Iceland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (103, 'fr', 'Islande');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (104, 'en', 'India');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (104, 'fr', 'Inde');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (105, 'en', 'Indonesia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (105, 'fr', 'Indonésie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (106, 'en', 'Iran');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (106, 'fr', 'Iran');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (107, 'en', 'Iraq');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (107, 'fr', 'Irak');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (108, 'en', 'Ireland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (108, 'fr', 'Irlande');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (109, 'en', 'Isle of Man');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (109, 'fr', 'Île de Man');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (110, 'en', 'Israel');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (110, 'fr', 'Israël');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (111, 'en', 'Italy');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (111, 'fr', 'Italie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (112, 'en', 'Jamaica');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (112, 'fr', 'Jamaïque');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (113, 'en', 'Japan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (113, 'fr', 'Japon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (114, 'en', 'Jersey');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (114, 'fr', 'Jersey');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (115, 'en', 'Jordan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (115, 'fr', 'Jordanie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (116, 'en', 'Kazakhstan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (116, 'fr', 'Kazakhstan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (117, 'en', 'Kenya');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (117, 'fr', 'Kenya');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (118, 'en', 'Kiribati');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (118, 'fr', 'Kiribati');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (119, 'en', 'Korea, Democratic People''s Republic of');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (119, 'fr', 'Corée, République populaire démocratique de');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (120, 'en', 'Korea, Republic of');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (120, 'fr', 'Corée, République de');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (121, 'en', 'Kuwait');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (121, 'fr', 'Koweït');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (122, 'en', 'Kyrgyzstan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (122, 'fr', 'Kyrgyzstan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (123, 'en', 'Lao, People''s Democratic Republic');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (123, 'fr', 'Laos, République démocratique populaire du');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (124, 'en', 'Latvia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (124, 'fr', 'Lettonie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (125, 'en', 'Lebanon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (125, 'fr', 'Liban');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (126, 'en', 'Lesotho');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (126, 'fr', 'Lesotho');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (127, 'en', 'Liberia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (127, 'fr', 'Libéria');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (128, 'en', 'Libya');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (128, 'fr', 'Libye');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (129, 'en', 'Liechtenstein');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (129, 'fr', 'Liechtenstein');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (130, 'en', 'Lithuania');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (130, 'fr', 'Lituanie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (131, 'en', 'Luxembourg');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (131, 'fr', 'Luxembourg');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (132, 'en', 'Macao');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (132, 'fr', 'Macao');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (133, 'en', 'Madagascar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (133, 'fr', 'Madagascar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (134, 'en', 'Malawi');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (134, 'fr', 'Malawi');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (135, 'en', 'Malaysia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (135, 'fr', 'Malaisie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (136, 'en', 'Maldives');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (136, 'fr', 'Maldives');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (137, 'en', 'Mali');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (137, 'fr', 'Mali');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (138, 'en', 'Malta');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (138, 'fr', 'Malte');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (139, 'en', 'Marshall Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (139, 'fr', 'Îles Marshall');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (140, 'en', 'Martinique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (140, 'fr', 'Martinique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (141, 'en', 'Mauritania');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (141, 'fr', 'Mauritanie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (142, 'en', 'Mauritius');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (142, 'fr', 'Île Maurice');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (143, 'en', 'Mayotte');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (143, 'fr', 'Mayotte');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (144, 'en', 'Mexico');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (144, 'fr', 'Mexique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (145, 'en', 'Micronesia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (145, 'fr', 'Micronésie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (146, 'en', 'Moldova');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (146, 'fr', 'Moldavie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (147, 'en', 'Monaco');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (147, 'fr', 'Monaco');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (148, 'en', 'Mongolia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (148, 'fr', 'Mongolie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (149, 'en', 'Montenegro');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (149, 'fr', 'Monténégro');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (150, 'en', 'Montserrat');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (150, 'fr', 'Montserrat');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (151, 'en', 'Morocco');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (151, 'fr', 'Maroc');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (152, 'en', 'Mozambique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (152, 'fr', 'Mozambique');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (153, 'en', 'Myanmar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (153, 'fr', 'Myanmar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (154, 'en', 'Namibia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (154, 'fr', 'Namibie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (155, 'en', 'Nauru');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (155, 'fr', 'Nauru');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (156, 'en', 'Nepal');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (156, 'fr', 'Népal');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (157, 'en', 'Netherlands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (157, 'fr', 'Pays-Bas');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (158, 'en', 'New Caledonia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (158, 'fr', 'Nouvelle Calédonie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (159, 'en', 'New Zealand');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (159, 'fr', 'Nouvelle-Zélande');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (160, 'en', 'Nicaragua');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (160, 'fr', 'Nicaragua');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (161, 'en', 'Niger');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (161, 'fr', 'Niger');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (162, 'en', 'Nigeria');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (162, 'fr', 'Nigéria');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (163, 'en', 'Niue');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (163, 'fr', 'Niue');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (164, 'en', 'Norfolk Island');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (164, 'fr', 'Île Norfolk');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (165, 'en', 'North Macedonia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (165, 'fr', 'Macédoine du Nord');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (166, 'en', 'Northern Mariana Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (166, 'fr', 'Îles Mariannes du Nord');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (167, 'en', 'Norway');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (167, 'fr', 'Norvège');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (168, 'en', 'Oman');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (168, 'fr', 'Oman');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (169, 'en', 'Pakistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (169, 'fr', 'Pakistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (170, 'en', 'Palau');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (170, 'fr', 'Palau');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (171, 'en', 'Palestine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (171, 'fr', 'Palestine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (172, 'en', 'Panama');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (172, 'fr', 'Panama');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (173, 'en', 'Papua New Guinea');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (173, 'fr', 'Papouasie-Nouvelle-Guinée');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (174, 'en', 'Paraguay');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (174, 'fr', 'Paraguay');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (175, 'en', 'Peru');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (175, 'fr', 'Pérou');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (176, 'en', 'Philippines');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (176, 'fr', 'Philippines');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (177, 'en', 'Pitcairn');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (177, 'fr', 'Pitcairn');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (178, 'en', 'Poland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (178, 'fr', 'Pologne');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (179, 'en', 'Portugal');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (179, 'fr', 'Portugal');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (180, 'en', 'Puerto Rico');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (180, 'fr', 'Puerto Rico');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (181, 'en', 'Qatar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (181, 'fr', 'Qatar');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (182, 'en', 'Réunion');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (182, 'fr', 'Réunion');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (183, 'en', 'Romania');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (183, 'fr', 'Roumanie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (184, 'en', 'Russian Federation');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (184, 'fr', 'Russie, Fédération de');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (185, 'en', 'Rwanda');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (185, 'fr', 'Rwanda');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (186, 'en', 'Saint Barthélemy');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (186, 'fr', 'Saint Barthélemy');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (187, 'en', 'Saint Helena');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (187, 'fr', 'Sainte-Hélène,');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (188, 'en', 'Saint Kitts and Nevis');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (188, 'fr', 'Saint Kitts et Nevis');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (189, 'en', 'Saint Lucia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (189, 'fr', 'Sainte-Lucie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (190, 'en', 'Saint Martin (French part)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (190, 'fr', 'Saint Martin (partie française)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (191, 'en', 'Saint Pierre and Miquelon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (191, 'fr', 'Saint Pierre et Miquelon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (192, 'en', 'Saint Vincent and the Grenadines');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (192, 'fr', 'Saint-Vincent-et-les-Grenadines');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (193, 'en', 'Samoa');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (193, 'fr', 'Samoa');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (194, 'en', 'San Marino');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (194, 'fr', 'Saint-Marin');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (195, 'en', 'Sao Tome and Principe');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (195, 'fr', 'Sao Tomé et Principe');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (196, 'en', 'Saudi Arabia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (196, 'fr', 'Arabie saoudite');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (197, 'en', 'Senegal');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (197, 'fr', 'Sénégal');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (198, 'en', 'Serbia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (198, 'fr', 'Serbie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (199, 'en', 'Seychelles');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (199, 'fr', 'Seychelles');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (200, 'en', 'Sierra Leone');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (200, 'fr', 'Sierra Leone');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (201, 'en', 'Singapore');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (201, 'fr', 'Singapour');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (202, 'en', 'Sint Maarten (Dutch part)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (202, 'fr', 'Saint Martin (partie néerlandaise)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (203, 'en', 'Slovakia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (203, 'fr', 'Slovaquie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (204, 'en', 'Slovenia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (204, 'fr', 'Slovénie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (205, 'en', 'Solomon Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (205, 'fr', 'Îles Solomon');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (206, 'en', 'Somalia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (206, 'fr', 'Somalie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (207, 'en', 'South Africa');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (207, 'fr', 'Afrique du Sud');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (208, 'en', 'South Georgia and the South Sandwich Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (208, 'fr', 'Géorgie du Sud et les îles Sandwich du Sud');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (209, 'en', 'South Sudan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (209, 'fr', 'Sud Soudan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (210, 'en', 'Spain');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (210, 'fr', 'Espagne');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (211, 'en', 'Sri Lanka');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (211, 'fr', 'Sri Lanka');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (212, 'en', 'Sudan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (212, 'fr', 'Soudan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (213, 'en', 'Suriname');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (213, 'fr', 'Suriname');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (214, 'en', 'Svalbard and Jan Mayen');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (214, 'fr', 'Svalbard et Jan Mayen');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (215, 'en', 'Sweden');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (215, 'fr', 'Suède');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (216, 'en', 'Switzerland');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (216, 'fr', 'Suisse');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (217, 'en', 'Syria');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (217, 'fr', 'Syrie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (218, 'en', 'Taiwan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (218, 'fr', 'Taïwan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (219, 'en', 'Tajikistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (219, 'fr', 'Tadjikistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (220, 'en', 'Tanzania');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (220, 'fr', 'Tanzanie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (221, 'en', 'Thailand');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (221, 'fr', 'Thaïlande');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (222, 'en', 'Timor-Leste');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (222, 'fr', 'Timor-Leste');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (223, 'en', 'Togo');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (223, 'fr', 'Togo');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (224, 'en', 'Tokelau');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (224, 'fr', 'Tokelau');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (225, 'en', 'Tonga');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (225, 'fr', 'Tonga');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (226, 'en', 'Trinidad and Tobago');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (226, 'fr', 'Trinité et Tobago');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (227, 'en', 'Tunisia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (227, 'fr', 'Tunisie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (228, 'en', 'Türkiye');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (228, 'fr', 'Turquie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (229, 'en', 'Turkmenistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (229, 'fr', 'Turkménistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (230, 'en', 'Turks and Caicos Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (230, 'fr', 'Îles Turks et Caicos');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (231, 'en', 'Tuvalu');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (231, 'fr', 'Tuvalu');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (232, 'en', 'Uganda');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (232, 'fr', 'Ouganda');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (233, 'en', 'Ukraine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (233, 'fr', 'Ukraine');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (234, 'en', 'United Arab Emirates');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (234, 'fr', 'Émirats arabes unis');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (235, 'en', 'United Kingdom');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (235, 'fr', 'Royaume-Uni');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (236, 'en', 'United States of America');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (236, 'fr', 'États-Unis');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (237, 'en', 'United States Minor Outlying Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (237, 'fr', 'Îles mineures éloignées des États-Unis');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (238, 'en', 'Uruguay');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (238, 'fr', 'Uruguay');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (239, 'en', 'Uzbekistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (239, 'fr', 'Ouzbékistan');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (240, 'en', 'Vanuatu');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (240, 'fr', 'Vanuatu');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (241, 'en', 'Venezuela');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (241, 'fr', 'Venezuela');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (242, 'en', 'Vietnam');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (242, 'fr', 'Vietnam');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (243, 'en', 'Virgin Islands (British)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (243, 'fr', 'Îles Vierges (britanniques)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (244, 'en', 'Virgin Islands (U.S.)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (244, 'fr', 'Îles Vierges (U.S.)');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (245, 'en', 'Wallis and Futuna');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (245, 'fr', 'Wallis et Futuna');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (246, 'en', 'Western Sahara');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (246, 'fr', 'Sahara occidental');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (247, 'en', 'Yemen');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (247, 'fr', 'Yémen');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (248, 'en', 'Zambia');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (248, 'fr', 'Zambie');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (249, 'en', 'Zimbabwe');
INSERT IGNORE INTO country_translation (country_id, language_code, country_name) VALUES (249, 'fr', 'Zimbabwe');
