-- Initialize booking_provider table

INSERT IGNORE INTO `booking_provider` (`name`) VALUES ('VIATOR');

-- Initialize country table

INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (1, '+93', 'af');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (2, '+355', 'al');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (3, '+213', 'dz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (4, '+1 684', 'as');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (5, '+376', 'ad');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (6, '+244', 'ao');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (7, '+1 264', 'ai');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (8, '+672', 'aq');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (9, '+1 268', 'ag');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (10, '+54', 'ar');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (11, '+374', 'am');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (12, '+297', 'aw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (13, '+247', 'ac');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (14, '+61', 'au');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (15, '+43', 'at');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (16, '+994', 'az');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (17, '+1 242', 'bs');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (18, '+973', 'bh');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (19, '+880', 'bd');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (20, '+1 246', 'bb');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (21, '+375', 'by');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (22, '+32', 'be');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (23, '+501', 'bz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (24, '+229', 'bj');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (25, '+1 441', 'bm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (26, '+975', 'bt');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (27, '+591', 'bo');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (28, '+387', 'ba');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (29, '+267', 'bw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (30, '+55', 'br');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (31, '+1 284', 'vg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (32, '+673', 'bn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (33, '+359', 'bg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (34, '+226', 'bf');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (35, '+95', 'mm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (36, '+257', 'bi');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (37, '+855', 'kh');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (38, '+237', 'cm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (40, '+1', 'ca');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (41, '+238', 'cv');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (42, '+1 345', 'ky');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (43, '+236', 'cf');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (44, '+235', 'td');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (45, '+56', 'cl');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (46, '+86', 'cn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (47, '+61', 'cx');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (48, '+61', 'cc');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (49, '+57', 'co');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (50, '+269', 'km');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (51, '+242', 'cg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (52, '+682', 'ck');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (53, '+506', 'cr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (54, '+385', 'hr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (55, '+53', 'cu');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (56, '+357', 'cy');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (57, '+420', 'cz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (58, '+243', 'cd');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (59, '+45', 'dk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (60, '+246', 'dg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (61, '+253', 'dj');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (62, '+1 767', 'dm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (63, '+1 809', 'do');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (64, '+593', 'ec');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (65, '+20', 'eg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (66, '+503', 'sv');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (67, '+240', 'gq');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (68, '+291', 'er');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (69, '+372', 'ee');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (70, '+251', 'et');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (71, '+500', 'fk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (72, '+298', 'fo');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (73, '+679', 'fj');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (74, '+358', 'fi');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (75, '+33', 'fr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (76, '+594', 'gf');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (77, '+689', 'pf');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (78, '+241', 'ga');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (79, '+220', 'gm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (80, '+995', 'ge');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (82, '+49', 'de');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (83, '+233', 'gh');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (84, '+350', 'gi');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (85, '+30', 'gr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (86, '+299', 'gl');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (87, '+1 473', 'gd');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (88, '+590', 'gp');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (89, '+1 671', 'gu');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (90, '+502', 'gt');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (91, '+224', 'gn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (92, '+245', 'gw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (93, '+592', 'gy');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (94, '+509', 'ht');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (95, '+39', 'va');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (96, '+504', 'hn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (97, '+852', 'hk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (98, '+36', 'hu');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (99, '+354', 'is');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (100, '+91', 'in');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (101, '+62', 'id');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (102, '+98', 'ir');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (103, '+964', 'iq');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (104, '+353', 'ie');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (105, '+44', 'im');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (106, '+972', 'il');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (107, '+39', 'it');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (108, '+225', 'ci');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (109, '+1 876', 'jm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (110, '+81', 'jp');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (111, '+44', 'je');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (112, '+962', 'jo');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (113, '+7', 'kz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (114, '+254', 'ke');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (115, '+686', 'ki');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (116, '+965', 'kw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (117, '+996', 'kg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (118, '+856', 'la');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (119, '+371', 'lv');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (120, '+961', 'lb');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (121, '+266', 'ls');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (122, '+231', 'lr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (124, '+218', 'ly');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (125, '+423', 'li');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (126, '+370', 'lt');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (127, '+352', 'lu');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (128, '+853', 'mo');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (129, '+389', 'mk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (130, '+261', 'mg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (131, '+265', 'mw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (132, '+60', 'my');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (133, '+960', 'mv');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (134, '+223', 'ml');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (135, '+356', 'mt');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (136, '+692', 'mh');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (137, '+596', 'mq');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (138, '+222', 'mr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (139, '+230', 'mu');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (140, '+262', 'yt');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (141, '+52', 'mx');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (142, '+691', 'fm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (143, '+373', 'md');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (144, '+377', 'mc');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (145, '+976', 'mn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (146, '+382', 'me');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (147, '+1 664', 'ms');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (148, '+212', 'ma');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (149, '+258', 'mz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (150, '+264', 'na');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (151, '+674', 'nr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (152, '+977', 'np');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (153, '+31', 'nl');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (154, '+599', 'an');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (155, '+687', 'nc');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (156, '+64', 'nz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (157, '+505', 'ni');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (158, '+227', 'ne');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (159, '+234', 'ng');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (160, '+683', 'nu');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (161, '+672', 'nf');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (162, '+850', 'kp');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (163, '+1 670', 'mp');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (164, '+47', 'no');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (166, '+968', 'om');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (167, '+92', 'pk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (168, '+680', 'pw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (169, '+970', 'ps');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (170, '+507', 'pa');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (171, '+675', 'pg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (172, '+595', 'py');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (173, '+51', 'pe');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (174, '+63', 'ph');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (175, '+870', 'pn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (176, '+48', 'pl');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (177, '+351', 'pt');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (178, '+1 787', 'pr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (179, '+974', 'qa');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (180, '+242', 'cg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (181, '+262', 're');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (182, '+40', 'ro');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (183, '+7', 'ru');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (184, '+250', 'rw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (185, '+590', 'bl');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (186, '+290', 'sh');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (187, '+1 869', 'kn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (188, '+1 758', 'lc');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (189, '+590', 'mf');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (190, '+508', 'pm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (191, '+1 784', 'vc');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (192, '+685', 'ws');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (193, '+378', 'sm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (194, '+239', 'st');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (195, '+966', 'sa');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (196, '+221', 'sn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (197, '+381', 'rs');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (198, '+248', 'sc');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (199, '+232', 'sl');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (200, '+65', 'sg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (201, '+1 721', 'sx');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (202, '+421', 'sk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (203, '+386', 'si');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (204, '+677', 'sb');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (205, '+252', 'so');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (206, '+27', 'za');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (208, '+82', 'kr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (209, '+211', 'ss');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (210, '+34', 'es');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (211, '+94', 'lk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (212, '+249', 'sd');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (213, '+597', 'sr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (214, '+47', 'sj');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (215, '+268', 'sz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (216, '+46', 'se');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (217, '+41', 'ch');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (218, '+963', 'sy');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (219, '+886', 'tw');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (220, '+992', 'tj');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (221, '+255', 'tz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (222, '+66', 'th');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (223, '+670', 'tl');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (224, '+228', 'tg');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (225, '+690', 'tk');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (226, '+676', 'to');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (227, '+1 868', 'tt');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (228, '+216', 'tn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (229, '+90', 'tr');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (230, '+993', 'tm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (231, '+1 649', 'tc');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (232, '+688', 'tv');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (233, '+256', 'ug');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (234, '+380', 'ua');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (235, '+971', 'ae');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (236, '+44', 'gb');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (237, '+1', 'us');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (238, '+598', 'uy');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (239, '+1 340', 'vi');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (240, '+998', 'uz');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (241, '+678', 'vu');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (242, '+58', 've');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (243, '+84', 'vn');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (244, '+681', 'wf');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (245, '+212', 'eh');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (246, '+967', 'ye');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (247, '+260', 'zm');
INSERT IGNORE INTO country (id, calling_code, iso_2_code) VALUES (248, '+263', 'zw');

-- Initialize country_translation table

INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (1, 'en', 'Afghanistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (1, 'fr', 'Afghanistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (2, 'en', 'Albania');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (2, 'fr', 'Albanie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (3, 'en', 'Algeria');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (3, 'fr', 'Algérie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (4, 'en', 'American Samoa');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (4, 'fr', 'Samoa américaines');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (5, 'en', 'Andorra');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (5, 'fr', 'Andorre');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (6, 'en', 'Angola');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (6, 'fr', 'Angola');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (7, 'en', 'Anguilla');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (7, 'fr', 'Anguilla');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (8, 'en', 'Antarctica');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (8, 'fr', 'Antarctique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (9, 'en', 'Antigua and Barbuda');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (9, 'fr', 'Antigua et Barbuda');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (10, 'en', 'Argentina');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (10, 'fr', 'Argentine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (11, 'en', 'Armenia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (11, 'fr', 'Arménie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (12, 'en', 'Aruba');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (12, 'fr', 'Aruba');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (13, 'en', 'Ascension Island');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (13, 'fr', 'Île de l''Ascension');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (14, 'en', 'Australia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (14, 'fr', 'Australie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (15, 'en', 'Austria');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (15, 'fr', 'Autriche');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (16, 'en', 'Azerbaijan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (16, 'fr', 'Azerbaïdjan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (17, 'en', 'Bahamas');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (17, 'fr', 'Bahamas');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (18, 'en', 'Bahrain');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (18, 'fr', 'Bahreïn');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (19, 'en', 'Bangladesh');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (19, 'fr', 'Bangladesh');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (20, 'en', 'Barbados');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (20, 'fr', 'Barbade');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (21, 'en', 'Belarus');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (21, 'fr', 'Biélorussie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (22, 'en', 'Belgium');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (22, 'fr', 'Belgique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (23, 'en', 'Belize');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (23, 'fr', 'Belize');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (24, 'en', 'Benin');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (24, 'fr', 'Bermudes');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (25, 'en', 'Bermuda');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (25, 'fr', 'Bermudes');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (26, 'en', 'Bhutan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (26, 'fr', 'Bhoutan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (27, 'en', 'Bolivia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (27, 'fr', 'Bolivie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (28, 'en', 'Bosnia and Herzegovina');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (28, 'fr', 'Bosnie et Herzégovine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (29, 'en', 'Botswana');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (29, 'fr', 'Botswana');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (30, 'en', 'Brazil');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (30, 'fr', 'Brésil');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (31, 'en', 'British Virgin Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (31, 'fr', 'Îles Vierges britanniques');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (32, 'en', 'Brunei');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (32, 'fr', 'Brunei');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (33, 'en', 'Bulgaria');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (33, 'fr', 'Bulgarie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (34, 'en', 'Burkina Faso');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (34, 'fr', 'Burkina Faso');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (35, 'en', 'Burma (Myanmar)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (35, 'fr', 'Birmanie (Myanmar)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (36, 'en', 'Burundi');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (36, 'fr', 'Burundi');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (37, 'en', 'Cambodia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (37, 'fr', 'Cambodge');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (38, 'en', 'Cameroon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (38, 'fr', 'Cameroun');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (40, 'en', 'Canada');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (40, 'fr', 'Canada');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (41, 'en', 'Cape Verde');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (41, 'fr', 'Cap Vert');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (42, 'en', 'Cayman Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (42, 'fr', 'Îles Caïmans');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (43, 'en', 'Central African Republic');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (43, 'fr', 'République Centrafricaine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (44, 'en', 'Chad');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (44, 'fr', 'Tchad');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (45, 'en', 'Chile');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (45, 'fr', 'Chili');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (46, 'en', 'China');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (46, 'fr', 'Chine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (47, 'en', 'Christmas Island');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (47, 'fr', 'Île Christmas');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (48, 'en', 'Cocos (Keeling) Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (48, 'fr', 'Îles Cocos (Keeling)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (49, 'en', 'Colombia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (49, 'fr', 'Colombie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (50, 'en', 'Comoros');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (50, 'fr', 'Comores');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (51, 'en', 'Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (51, 'fr', 'Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (52, 'en', 'Cook Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (52, 'fr', 'Îles Cook ');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (53, 'en', 'Costa Rica');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (53, 'fr', 'Costa Rica');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (54, 'en', 'Croatia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (54, 'fr', 'Croatie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (55, 'en', 'Cuba');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (55, 'fr', 'Cuba');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (56, 'en', 'Cyprus');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (56, 'fr', 'Chypre');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (57, 'en', 'Czech Republic');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (57, 'fr', 'République tchèque');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (58, 'en', 'Democratic Republic of the Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (58, 'fr', 'République démocratique du Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (59, 'en', 'Denmark');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (59, 'fr', 'Danemark');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (60, 'en', 'Diego Garcia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (60, 'fr', 'Diego Garcia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (61, 'en', 'Djibouti');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (61, 'fr', 'Djibouti');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (62, 'en', 'Dominica');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (62, 'fr', 'Dominique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (63, 'en', 'Dominican Republic');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (63, 'fr', 'République dominicaine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (64, 'en', 'Ecuador');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (64, 'fr', 'Equateur');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (65, 'en', 'Egypt');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (65, 'fr', 'Égypte');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (66, 'en', 'El Salvador');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (66, 'fr', 'El Salvador');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (67, 'en', 'Equatorial Guinea');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (67, 'fr', 'Guinée équatoriale');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (68, 'en', 'Eritrea');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (68, 'fr', 'Erythrée');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (69, 'en', 'Estonia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (69, 'fr', 'Estonie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (70, 'en', 'Ethiopia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (70, 'fr', 'Éthiopie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (71, 'en', 'Falkland Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (71, 'fr', 'Îles Falkland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (72, 'en', 'Faroe Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (72, 'fr', 'Îles Féroé');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (73, 'en', 'Fiji');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (73, 'fr', 'Fiji');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (74, 'en', 'Finland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (74, 'fr', 'Finlande');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (75, 'en', 'France');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (75, 'fr', 'France');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (76, 'en', 'French Guiana');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (76, 'fr', 'Guyane française');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (77, 'en', 'French Polynesia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (77, 'fr', 'Polynésie française');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (78, 'en', 'Gabon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (78, 'fr', 'Gabon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (79, 'en', 'Gambia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (79, 'fr', 'Gambie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (80, 'en', 'Georgia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (80, 'fr', 'Géorgie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (82, 'en', 'Germany');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (82, 'fr', 'Allemagne');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (83, 'en', 'Ghana');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (83, 'fr', 'Ghana');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (84, 'en', 'Gibraltar');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (84, 'fr', 'Gibraltar');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (85, 'en', 'Greece');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (85, 'fr', 'Grèce');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (86, 'en', 'Greenland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (86, 'fr', 'Groenland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (87, 'en', 'Grenada');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (87, 'fr', 'Grenade');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (88, 'en', 'Guadeloupe');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (88, 'fr', 'Guadeloupe');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (89, 'en', 'Guam');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (89, 'fr', 'Guam');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (90, 'en', 'Guatemala');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (90, 'fr', 'Guatemala');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (91, 'en', 'Guinea');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (91, 'fr', 'Guinée');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (92, 'en', 'Guinea-Bissau');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (92, 'fr', 'Guinée-Bissau');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (93, 'en', 'Guyana');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (93, 'fr', 'Guyana');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (94, 'en', 'Haiti');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (94, 'fr', 'Haïti');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (95, 'en', 'Holy See (Vatican City)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (95, 'fr', 'Saint-Siège (Cité du Vatican)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (96, 'en', 'Honduras');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (96, 'fr', 'Honduras');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (97, 'en', 'Hong Kong');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (97, 'fr', 'Hong Kong');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (98, 'en', 'Hungary');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (98, 'fr', 'Hongrie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (99, 'en', 'Iceland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (99, 'fr', 'Islande');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (100, 'en', 'India');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (100, 'fr', 'Inde');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (101, 'en', 'Indonesia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (101, 'fr', 'Indonésie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (102, 'en', 'Iran');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (102, 'fr', 'Iran');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (103, 'en', 'Iraq');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (103, 'fr', 'Irak');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (104, 'en', 'Ireland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (104, 'fr', 'Irlande');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (105, 'en', 'Isle of Man');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (105, 'fr', 'Île de Man');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (106, 'en', 'Israel');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (106, 'fr', 'Israël');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (107, 'en', 'Italy');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (107, 'fr', 'Italie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (108, 'en', 'Ivory Coast');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (108, 'fr', 'Côte d''Ivoire');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (109, 'en', 'Jamaica');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (109, 'fr', 'Jamaïque');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (110, 'en', 'Japan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (110, 'fr', 'Japon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (111, 'en', 'Jersey');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (111, 'fr', 'Jersey');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (112, 'en', 'Jordan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (112, 'fr', 'Jordanie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (113, 'en', 'Kazakhstan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (113, 'fr', 'Kazakhstan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (114, 'en', 'Kenya');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (114, 'fr', 'Kenya');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (115, 'en', 'Kiribati');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (115, 'fr', 'Kiribati');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (116, 'en', 'Kuwait');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (116, 'fr', 'Koweït');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (117, 'en', 'Kyrgyzstan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (117, 'fr', 'Kirghizistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (118, 'en', 'Laos');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (118, 'fr', 'Laos');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (119, 'en', 'Latvia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (119, 'fr', 'Lettonie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (120, 'en', 'Lebanon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (120, 'fr', 'Liban');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (121, 'en', 'Lesotho');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (121, 'fr', 'Lesotho');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (122, 'en', 'Liberia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (122, 'fr', 'Libéria');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (124, 'en', 'Libya');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (124, 'fr', 'Libye');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (125, 'en', 'Liechtenstein');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (125, 'fr', 'Liechtenstein');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (126, 'en', 'Lithuania');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (126, 'fr', 'Lituanie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (127, 'en', 'Luxembourg');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (127, 'fr', 'Luxembourg');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (128, 'en', 'Macau');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (128, 'fr', 'Macao');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (129, 'en', 'Macedonia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (129, 'fr', 'Macédoine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (130, 'en', 'Madagascar');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (130, 'fr', 'Madagascar');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (131, 'en', 'Malawi');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (131, 'fr', 'Malawi');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (132, 'en', 'Malaysia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (132, 'fr', 'Malaisie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (133, 'en', 'Maldives');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (133, 'fr', 'Maldives');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (134, 'en', 'Mali');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (134, 'fr', 'Mali');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (135, 'en', 'Malta');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (135, 'fr', 'Malte');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (136, 'en', 'Marshall Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (136, 'fr', 'Îles Marshall');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (137, 'en', 'Martinique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (137, 'fr', 'Martinique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (138, 'en', 'Mauritania');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (138, 'fr', 'Mauritanie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (139, 'en', 'Mauritius');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (139, 'fr', 'Île Maurice');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (140, 'en', 'Mayotte');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (140, 'fr', 'Mayotte');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (141, 'en', 'Mexico');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (141, 'fr', 'Mexique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (142, 'en', 'Micronesia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (142, 'fr', 'Micronésie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (143, 'en', 'Moldova');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (143, 'fr', 'Moldavie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (144, 'en', 'Monaco');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (144, 'fr', 'Monaco');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (145, 'en', 'Mongolia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (145, 'fr', 'Mongolie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (146, 'en', 'Montenegro');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (146, 'fr', 'Monténégro');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (147, 'en', 'Montserrat');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (147, 'fr', 'Montserrat');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (148, 'en', 'Morocco');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (148, 'fr', 'Maroc');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (149, 'en', 'Mozambique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (149, 'fr', 'Mozambique');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (150, 'en', 'Namibia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (150, 'fr', 'Namibie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (151, 'en', 'Nauru');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (151, 'fr', 'Nauru');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (152, 'en', 'Nepal');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (152, 'fr', 'Népal');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (153, 'en', 'Netherlands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (153, 'fr', 'Pays-Bas');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (154, 'en', 'Netherlands Antilles');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (154, 'fr', 'Antilles néerlandaises');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (155, 'en', 'New Caledonia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (155, 'fr', 'Nouvelle Calédonie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (156, 'en', 'New Zealand');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (156, 'fr', 'Nouvelle Zélande');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (157, 'en', 'Nicaragua');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (157, 'fr', 'Nicaragua');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (158, 'en', 'Niger');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (158, 'fr', 'Niger');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (159, 'en', 'Nigeria');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (159, 'fr', 'Nigéria');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (160, 'en', 'Niue');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (160, 'fr', 'Niue');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (161, 'en', 'Norfolk Island');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (161, 'fr', 'Île Norfolk');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (162, 'en', 'North Korea');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (162, 'fr', 'Corée du Nord');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (163, 'en', 'Northern Mariana Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (163, 'fr', 'Îles Mariannes du Nord');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (164, 'en', 'Norway');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (164, 'fr', 'Norvège');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (166, 'en', 'Oman');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (166, 'fr', 'Oman');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (167, 'en', 'Pakistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (167, 'fr', 'Pakistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (168, 'en', 'Palau');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (168, 'fr', 'Palau');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (169, 'en', 'Palestine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (169, 'fr', 'Palestine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (170, 'en', 'Panama');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (170, 'fr', 'Panama');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (171, 'en', 'Papua New Guinea');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (171, 'fr', 'Papouasie-Nouvelle-Guinée');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (172, 'en', 'Paraguay');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (172, 'fr', 'Paraguay');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (173, 'en', 'Peru');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (173, 'fr', 'Pérou');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (174, 'en', 'Philippines');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (174, 'fr', 'Philippines');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (175, 'en', 'Pitcairn Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (175, 'fr', ' Pitcairn');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (176, 'en', 'Poland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (176, 'fr', 'Pologne');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (177, 'en', 'Portugal');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (177, 'fr', 'Portugal');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (178, 'en', 'Puerto Rico');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (178, 'fr', 'Puerto Rico');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (179, 'en', 'Qatar');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (179, 'fr', 'Qatar');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (180, 'en', 'Republic of the Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (180, 'fr', 'République du Congo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (181, 'en', 'Reunion Island');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (181, 'fr', 'Île de la Réunion');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (182, 'en', 'Romania');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (182, 'fr', 'Roumanie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (183, 'en', 'Russia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (183, 'fr', 'Russie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (184, 'en', 'Rwanda');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (184, 'fr', 'Rwanda');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (185, 'en', 'Saint Barthelemy');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (185, 'fr', 'Saint-Barthélemy');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (186, 'en', 'Saint Helena');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (186, 'fr', 'Sainte-Hélène');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (187, 'en', 'Saint Kitts and Nevis');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (187, 'fr', 'Saint Kitts et Nevis');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (188, 'en', 'Saint Lucia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (188, 'fr', 'Sainte-Lucie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (189, 'en', 'Saint Martin');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (189, 'fr', 'Saint Martin');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (190, 'en', 'Saint Pierre and Miquelon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (190, 'fr', 'Saint Pierre et Miquelon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (191, 'en', 'Saint Vincent and the Grenadines');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (191, 'fr', 'Saint Vincent et les Grenadines');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (192, 'en', 'Samoa');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (192, 'fr', 'Samoa');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (193, 'en', 'San Marino');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (193, 'fr', 'Saint-Marin');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (194, 'en', 'Sao Tome and Principe');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (194, 'fr', 'Sao Tomé et Principe');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (195, 'en', 'Saudi Arabia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (195, 'fr', 'Arabie Saoudite');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (196, 'en', 'Senegal');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (196, 'fr', 'Sénégal');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (197, 'en', 'Serbia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (197, 'fr', 'Serbie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (198, 'en', 'Seychelles');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (198, 'fr', 'Seychelles');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (199, 'en', 'Sierra Leone');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (199, 'fr', 'Sierra Leone');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (200, 'en', 'Singapore');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (200, 'fr', 'Singapour');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (201, 'en', 'Sint Maarten');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (201, 'fr', 'Sint Maarten');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (202, 'en', 'Slovakia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (202, 'fr', 'Slovaquie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (203, 'en', 'Slovenia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (203, 'fr', 'Slovénie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (204, 'en', 'Solomon Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (204, 'fr', 'Îles Salomon');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (205, 'en', 'Somalia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (205, 'fr', 'Somalie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (206, 'en', 'South Africa');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (206, 'fr', 'Afrique du Sud');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (208, 'en', 'South Korea');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (208, 'fr', 'Corée du Sud');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (209, 'en', 'South Sudan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (209, 'fr', 'Soudan du Sud');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (210, 'en', 'Spain');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (210, 'fr', 'Espagne');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (211, 'en', 'Sri Lanka');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (211, 'fr', 'Sri Lanka');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (212, 'en', 'Sudan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (212, 'fr', 'Soudan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (213, 'en', 'Suriname');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (213, 'fr', 'Suriname');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (214, 'en', 'Svalbard');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (214, 'fr', 'Svalbard');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (215, 'en', 'Swaziland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (215, 'fr', 'Swaziland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (216, 'en', 'Sweden');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (216, 'fr', 'Suède');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (217, 'en', 'Switzerland');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (217, 'fr', 'Suisse');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (218, 'en', 'Syria');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (218, 'fr', 'Syrie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (219, 'en', 'Taiwan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (219, 'fr', 'Taïwan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (220, 'en', 'Tajikistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (220, 'fr', 'Tadjikistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (221, 'en', 'Tanzania');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (221, 'fr', 'Tanzanie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (222, 'en', 'Thailand');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (222, 'fr', 'Thaïlande');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (223, 'en', 'Timor-Leste (East Timor)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (223, 'fr', 'Timor-Leste (Timor oriental)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (224, 'en', 'Togo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (224, 'fr', 'Togo');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (225, 'en', 'Tokelau');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (225, 'fr', 'Tokelau');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (226, 'en', 'Tonga Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (226, 'fr', 'Tonga (Îles)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (227, 'en', 'Trinidad and Tobago');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (227, 'fr', 'Trinité et Tobago');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (228, 'en', 'Tunisia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (228, 'fr', 'Tunisie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (229, 'en', 'Turkey');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (229, 'fr', 'Turquie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (230, 'en', 'Turkmenistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (230, 'fr', 'Turkménistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (231, 'en', 'Turks and Caicos Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (231, 'fr', 'Turks et Caicos (Îles)');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (232, 'en', 'Tuvalu');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (232, 'fr', 'Tuvalu');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (233, 'en', 'Uganda');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (233, 'fr', 'Ouganda');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (234, 'en', 'Ukraine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (234, 'fr', 'Ukraine');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (235, 'en', 'United Arab Emirates');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (235, 'fr', 'Emirats Arabes Unis');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (236, 'en', 'United Kingdom');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (236, 'fr', 'Royaume-Uni');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (237, 'en', 'United States');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (237, 'fr', 'États-Unis');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (238, 'en', 'Uruguay');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (238, 'fr', 'Uruguay');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (239, 'en', 'US Virgin Islands');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (239, 'fr', 'Îles Vierges américaines');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (240, 'en', 'Uzbekistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (240, 'fr', 'Ouzbékistan');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (241, 'en', 'Vanuatu');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (241, 'fr', 'Vanuatu');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (242, 'en', 'Venezuela');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (242, 'fr', 'Venezuela');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (243, 'en', 'Vietnam');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (243, 'fr', 'Vietnam');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (244, 'en', 'Wallis and Futuna');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (244, 'fr', 'Wallis et Futuna');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (245, 'en', 'Western Sahara');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (245, 'fr', 'Sahara occidental');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (246, 'en', 'Yemen');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (246, 'fr', 'Yémen');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (247, 'en', 'Zambia');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (247, 'fr', 'Zambie');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (248, 'en', 'Zimbabwe');
INSERT IGNORE INTO country_translation (country_id, language_code, name) VALUES (248, 'fr', 'Zimbabwe');
