package com.asialocalguide.gateway.viator.util;

import java.util.HashMap;
import java.util.Map;

public class Iso2CodeLookupMap {

  private static final Map<String, String> map = new HashMap<>();

  public static String getIso2Code(String country) {
    if (country == null || country.isEmpty()) {
      return null;
    }
    return map.get(country);
  }

  private Iso2CodeLookupMap() {}

  static {
    map.put("Afghanistan", "af");
    map.put("Albania", "al");
    map.put("Algeria", "dz");
    map.put("American Samoa", "as");
    map.put("Andorra", "ad");
    map.put("Angola", "ao");
    map.put("Anguilla", "ai");
    map.put("Antarctica", "aq");
    map.put("Antigua and Barbuda", "ag");
    map.put("Argentina", "ar");
    map.put("Armenia", "am");
    map.put("Aruba", "aw");
    map.put("Ascension Island", "ac");
    map.put("Australia", "au");
    map.put("Austria", "at");
    map.put("Azerbaijan", "az");
    map.put("Bahamas", "bs");
    map.put("Bahrain", "bh");
    map.put("Bangladesh", "bd");
    map.put("Barbados", "bb");
    map.put("Belarus", "by");
    map.put("Belgium", "be");
    map.put("Belize", "bz");
    map.put("Benin", "bj");
    map.put("Bermuda", "bm");
    map.put("Bhutan", "bt");
    map.put("Bolivia", "bo");
    map.put("Bosnia and Herzegovina", "ba");
    map.put("Botswana", "bw");
    map.put("Brazil", "br");
    map.put("British Virgin Islands", "vg");
    map.put("Brunei", "bn");
    map.put("Bulgaria", "bg");
    map.put("Burkina Faso", "bf");
    map.put("Myanmar", "mm");
    map.put("Burundi", "bi");
    map.put("Cambodia", "kh");
    map.put("Cameroon", "cm");
    map.put("Canada", "ca");
    map.put("Cape Verde", "cv");
    map.put("Cayman Islands", "ky");
    map.put("Central African Republic", "cf");
    map.put("Chad", "td");
    map.put("Chile", "cl");
    map.put("China", "cn");
    map.put("Christmas Island", "cx");
    map.put("Cocos (Keeling) Islands", "cc");
    map.put("Colombia", "co");
    map.put("Comoros", "km");
    map.put("Congo", "cg");
    map.put("Cook Islands", "ck");
    map.put("Costa Rica", "cr");
    map.put("Croatia", "hr");
    map.put("Cuba", "cu");
    map.put("Cyprus", "cy");
    map.put("Czech Republic", "cz");
    map.put("Democratic Republic of Congo", "cd");
    map.put("Denmark", "dk");
    map.put("Diego Garcia", "dg");
    map.put("Djibouti", "dj");
    map.put("Dominica", "dm");
    map.put("Dominican Republic", "do");
    map.put("Ecuador", "ec");
    map.put("Egypt", "eg");
    map.put("El Salvador", "sv");
    map.put("Equatorial Guinea", "gq");
    map.put("Eritrea", "er");
    map.put("Estonia", "ee");
    map.put("Ethiopia", "et");
    map.put("Falkland Islands", "fk");
    map.put("Faroe Islands", "fo");
    map.put("Fiji", "fj");
    map.put("Finland", "fi");
    map.put("France", "fr");
    map.put("French Guiana", "gf");
    map.put("French Polynesia", "pf");
    map.put("Gabon", "ga");
    map.put("Gambia", "gm");
    map.put("Georgia", "ge");
    map.put("Germany", "de");
    map.put("Ghana", "gh");
    map.put("Gibraltar", "gi");
    map.put("Greece", "gr");
    map.put("Greenland", "gl");
    map.put("Grenada", "gd");
    map.put("Guadeloupe", "gp");
    map.put("Guam", "gu");
    map.put("Guatemala", "gt");
    map.put("Guinea", "gn");
    map.put("Guinea-Bissau", "gw");
    map.put("Guyana", "gy");
    map.put("Haiti", "ht");
    map.put("Holy See (Vatican City)", "va");
    map.put("Honduras", "hn");
    map.put("Hong Kong", "hk");
    map.put("Hungary", "hu");
    map.put("Iceland", "is");
    map.put("India", "in");
    map.put("Indonesia", "id");
    map.put("Iran", "ir");
    map.put("Iraq", "iq");
    map.put("Ireland", "ie");
    map.put("Isle of Man", "im");
    map.put("Israel", "il");
    map.put("Italy", "it");
    map.put("Côte d’Ivoire", "ci");
    map.put("Jamaica", "jm");
    map.put("Japan", "jp");
    map.put("Jersey", "je");
    map.put("Jordan", "jo");
    map.put("Kazakhstan", "kz");
    map.put("Kenya", "ke");
    map.put("Kiribati", "ki");
    map.put("Kuwait", "kw");
    map.put("Kyrgyzstan", "kg");
    map.put("Laos", "la");
    map.put("Latvia", "lv");
    map.put("Lebanon", "lb");
    map.put("Lesotho", "ls");
    map.put("Liberia", "lr");
    map.put("Libya", "ly");
    map.put("Liechtenstein", "li");
    map.put("Lithuania", "lt");
    map.put("Luxembourg", "lu");
    map.put("Macau", "mo");
    map.put("Macedonia", "mk");
    map.put("Madagascar", "mg");
    map.put("Malawi", "mw");
    map.put("Malaysia", "my");
    map.put("Maldives", "mv");
    map.put("Mali", "ml");
    map.put("Malta", "mt");
    map.put("Marshall Islands", "mh");
    map.put("Martinique", "mq");
    map.put("Mauritania", "mr");
    map.put("Mauritius", "mu");
    map.put("Mayotte", "yt");
    map.put("Mexico", "mx");
    map.put("Micronesia", "fm");
    map.put("Moldova", "md");
    map.put("Monaco", "mc");
    map.put("Mongolia", "mn");
    map.put("Montenegro", "me");
    map.put("Montserrat", "ms");
    map.put("Morocco", "ma");
    map.put("Mozambique", "mz");
    map.put("Namibia", "na");
    map.put("Nauru", "nr");
    map.put("Nepal", "np");
    map.put("Netherlands", "nl");
    map.put("Netherlands Antilles", "an");
    map.put("New Caledonia", "nc");
    map.put("New Zealand", "nz");
    map.put("Nicaragua", "ni");
    map.put("Niger", "ne");
    map.put("Nigeria", "ng");
    map.put("Niue", "nu");
    map.put("Norfolk Island", "nf");
    map.put("North Korea", "kp");
    map.put("Northern Mariana Islands", "mp");
    map.put("Norway", "no");
    map.put("Oman", "om");
    map.put("Pakistan", "pk");
    map.put("Palau", "pw");
    map.put("Palestine", "ps");
    map.put("Panama", "pa");
    map.put("Papua New Guinea", "pg");
    map.put("Paraguay", "py");
    map.put("Peru", "pe");
    map.put("Philippines", "ph");
    map.put("Pitcairn Islands", "pn");
    map.put("Poland", "pl");
    map.put("Portugal", "pt");
    map.put("Puerto Rico", "pr");
    map.put("Qatar", "qa");
    map.put("Republic of the Congo", "cg");
    map.put("Reunion Island", "re");
    map.put("Romania", "ro");
    map.put("Russia", "ru");
    map.put("Rwanda", "rw");
    map.put("Saint Barthelemy", "bl");
    map.put("Saint Helena", "sh");
    map.put("St Kitts and Nevis", "kn");
    map.put("St Lucia", "lc");
    map.put("Saint Martin", "mf");
    map.put("Saint Pierre and Miquelon", "pm");
    map.put("St Vincent and the Grenadines", "vc");
    map.put("Samoa", "ws");
    map.put("San Marino", "sm");
    map.put("São Tomé and Príncipe", "st");
    map.put("Saudi Arabia", "sa");
    map.put("Senegal", "sn");
    map.put("Serbia", "rs");
    map.put("Seychelles", "sc");
    map.put("Sierra Leone", "sl");
    map.put("Singapore", "sg");
    map.put("St Maarten", "sx");
    map.put("Slovakia", "sk");
    map.put("Slovenia", "si");
    map.put("Solomon Islands", "sb");
    map.put("Somalia", "so");
    map.put("South Africa", "za");
    map.put("South Korea", "kr");
    map.put("South Sudan", "ss");
    map.put("Spain", "es");
    map.put("Sri Lanka", "lk");
    map.put("Sudan", "sd");
    map.put("Suriname", "sr");
    map.put("Svalbard", "sj");
    map.put("Eswatini (Swaziland)", "sz");
    map.put("Sweden", "se");
    map.put("Switzerland", "ch");
    map.put("Syria", "sy");
    map.put("Taiwan", "tw");
    map.put("Tajikistan", "tj");
    map.put("Tanzania", "tz");
    map.put("Thailand", "th");
    map.put("Timor-Leste (East Timor)", "tl");
    map.put("Togo", "tg");
    map.put("Tokelau", "tk");
    map.put("Tonga", "to");
    map.put("Trinidad and Tobago", "tt");
    map.put("Tunisia", "tn");
    map.put("Turkey", "tr");
    map.put("Turkmenistan", "tm");
    map.put("Turks and Caicos", "tc");
    map.put("Tuvalu", "tv");
    map.put("Uganda", "ug");
    map.put("Ukraine", "ua");
    map.put("United Arab Emirates", "ae");
    map.put("United Kingdom", "gb");
    map.put("USA", "us");
    map.put("Uruguay", "uy");
    map.put("US Virgin Islands", "vi");
    map.put("Uzbekistan", "uz");
    map.put("Vanuatu", "vu");
    map.put("Venezuela", "ve");
    map.put("Vietnam", "vn");
    map.put("Wallis and Futuna", "wf");
    map.put("Western Sahara", "eh");
    map.put("Yemen", "ye");
    map.put("Zambia", "zm");
    map.put("Zimbabwe", "zw");

    map.put("England", "gb");
    map.put("Wales", "gb");
    map.put("Scotland", "gb");
    map.put("Northern Ireland", "gb");
  }
}
